declare module 'vue-picture-input'
declare module 'bootstrap-vue/es/components'
declare module 'bootstrap-vue/esm/components/alert/alert'
declare module 'bootstrap-vue/esm/components/button/button'
declare module 'bootstrap-vue/esm/components/card/card'
declare module 'bootstrap-vue/esm/components/card/card-body'
declare module 'bootstrap-vue/esm/components/card/card-footer'
declare module 'bootstrap-vue/esm/components/card/card-header'
declare module 'bootstrap-vue/esm/components/collapse/collapse'
declare module 'bootstrap-vue/esm/components/dropdown/dropdown'
declare module 'bootstrap-vue/esm/components/form-select'
declare module 'bootstrap-vue/esm/components/dropdown/dropdown-item'
declare module 'bootstrap-vue/esm/components/form-input/form-input'
declare module 'bootstrap-vue/esm/components/modal/modal'
declare module 'bootstrap-vue/esm/components/tooltip/tooltip'
declare module 'bootstrap-vue/esm/components/button-group/button-group'
declare module 'bootstrap-vue/esm/components/button-toolbar/button-toolbar'

declare module '@progress/kendo-datasource-vue-wrapper/dist/es/KendoDataSource/index'
declare module '@progress/kendo-dropdowns-vue-wrapper/dist/es/KendoAutoComplete/index'
declare module '@progress/kendo-dropdowns-vue-wrapper/dist/es/KendoDropDownList/index'
declare module '@progress/kendo-upload-vue-wrapper/dist/es/KendoUpload/index'
declare module '@progress/kendo-layout-vue-wrapper/dist/es/KendoPanelBar/index'
declare module '@progress/kendo-inputs-vue-wrapper/dist/es/KendoSwitch/index'
declare module '@progress/kendo-inputs-vue-wrapper/dist/es/KendoNumericTextBox/index'
declare module '@progress/kendo-inputs-vue'
declare module '@progress/kendo-vue-layout'

//declare module '@progress/kendo-dateinputs-vue-wrapper'

//declare module 'imagesloaded'
declare module 'vuejs-datepicker'
declare module 'vue-images-loaded'
declare module 'bootstrap-vue/esm/directives'
declare module 'bootstrap-vue/esm/directives/toggle/toggle'
declare module 'bootstrap-vue/esm/directives/modal/modal'

declare module '@progress/kendo-ui'
