export enum Roles {
  Administrator = 1,
  Scheduler,
  AdminSupport,
  Bookkeeper,
  ServiceTech,
  ServiceTech2,
  ServiceManager,
  InsuranceAdjuster,
  BillingContact,
  AdjusterDirector,
  AdjusterManager,
  ServiceDirector,
  EagleView,
}
