// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonPrimary: typeof import('./components/shared/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./components/shared/ButtonSecondary.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    ExampleClassComponent: typeof import('./components/ExampleClassComponent.vue')['default']
    Feature: typeof import('./components/Feature.vue')['default']
    Greeting: typeof import('./components/Greeting.vue')['default']
    Heading1: typeof import('./components/shared/Heading1.vue')['default']
    Heading2: typeof import('./components/shared/Heading2.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    InputFocus: typeof import('./components/InputFocus.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    OutBuilding: typeof import('./components/OutBuilding.vue')['default']
    Outbuildings: typeof import('./components/Outbuildings.vue')['default']
    ProjectInspectionForm: typeof import('./components/ProjectInspectionForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestComponent: typeof import('./components/TestComponent.vue')['default']
  }
}
