// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/AppButton.vue')['default']
    Assignment: typeof import('./components/Assignment.vue')['default']
    AssignmentCreate: typeof import('./components/AssignmentCreate.vue')['default']
    AssignmentList: typeof import('./components/AssignmentList.vue')['default']
    Assignments: typeof import('./components/Assignments.vue')['default']
    ButtonPrimary: typeof import('./components/shared/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./components/shared/ButtonSecondary.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    ExampleClassComponent: typeof import('./components/ExampleClassComponent.vue')['default']
    Feature: typeof import('./components/Feature.vue')['default']
    Greeting: typeof import('./components/Greeting.vue')['default']
    Heading1: typeof import('./components/shared/Heading1.vue')['default']
    Heading2: typeof import('./components/shared/Heading2.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    InputFocus: typeof import('./components/InputFocus.vue')['default']
    InputFocusComponent: typeof import('./components/InputFocusComponent.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NewOutBuilding: typeof import('./components/NewOutBuilding.vue')['default']
    OutBuilding: typeof import('./components/OutBuilding.vue')['default']
    OutBuildingComponent: typeof import('./components/OutBuildingComponent.vue')['default']
    OutBuildingList: typeof import('./components/OutBuildingList.vue')['default']
    Outbuildings: typeof import('./components/Outbuildings.vue')['default']
    OutBuildings: typeof import('./components/OutBuildings.vue')['default']
    OutBuildingsComponent: typeof import('./components/OutBuildingsComponent.vue')['default']
    OutBuildingsList: typeof import('./components/OutBuildingsList.vue')['default']
    ProjectInspectionForm: typeof import('./components/ProjectInspectionForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestComponent: typeof import('./components/TestComponent.vue')['default']
  }
}
